version: '3.8'

networks:
  leonet:

services:
  postgres:
    container_name: 'posgres-db'
    image: postgres:13
    ports:
      # local : container
      - 5434:5432
    environment:
      POSTGRES_DB: nest
      POSTGRES_USER: postgres'
      POSTGRES_PASSWORD: 123
    networks:
      - leonet
